import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useQueries } from '@tanstack/react-query';
import { Activity, ShieldCheck, X } from 'lucide-react';
import { drugApi } from '../../api/drugApi';
import { Card, CardBody, CardHeader, PageHeader } from '../../components/ui/Card';
import { Button } from '../../components/ui/Button';
import { SeverityBadge } from '../../components/ui/Badge';
import { Alert, EmptyState, LoadingSkeleton } from '../../components/ui/Feedback';
import { DrugSearchSelect } from '../../components/drugs/DrugSearchSelect';
import { drugDisplayName } from '../../lib/format';
import { sortBySeverity } from '../../lib/severity';

/**
 * Catalog-level pair screening. It does not consider allergies, conditions or
 * labs — a patient safety check does that.
 */
export default function InteractionCheckerPage() {
  const [selected, setSelected] = useState([]);

  const results = useQueries({
    queries: selected.map((drug) => ({
      queryKey: ['drug-interactions', drug.id],
      queryFn: () => drugApi.interactions(drug.id),
    })),
  });

  const loading = results.some((result) => result.isLoading);
  const selectedIds = new Set(selected.map((drug) => drug.id));

  const pairs = [];
  const seen = new Set();
  results.forEach((result, index) => {
    const source = selected[index];
    (result.data || []).forEach((interaction) => {
      const other = interaction.otherDrug;
      if (!other || !selectedIds.has(other.id)) return;
      const key = [source.id, other.id].sort().join(':') + interaction.id;
      if (seen.has(key)) return;
      seen.add(key);
      pairs.push({ ...interaction, drugA: source, drugB: other });
    });
  });

  const add = (drug) => setSelected((current) => (current.some((item) => item.id === drug.id) ? current : [...current, drug]));
  const remove = (drugId) => setSelected((current) => current.filter((drug) => drug.id !== drugId));

  return (
    <>
      <PageHeader
        title="Interaction checker"
        description="Screen two or more catalog drugs against curated drug–drug rules."
        actions={
          <Button as={Link} to="/safety" variant="secondary" icon={ShieldCheck}>
            Full patient safety check
          </Button>
        }
      />

      <div className="grid gap-6 lg:grid-cols-[22rem_minmax(0,1fr)]">
        <Card>
          <CardHeader title="Selected drugs" description="Add at least two drugs to screen." />
          <CardBody className="space-y-4">
            <DrugSearchSelect onSelect={add} />
            {selected.length === 0 ? (
              <p className="text-sm text-ink-muted">Nothing selected yet.</p>
            ) : (
              <ul className="space-y-2">
                {selected.map((drug) => (
                  <li key={drug.id} className="flex items-center justify-between gap-2 rounded-lg border border-line px-3 py-2">
                    <span className="min-w-0 truncate text-sm text-ink">{drugDisplayName(drug)}</span>
                    <button
                      type="button"
                      onClick={() => remove(drug.id)}
                      aria-label={`Remove ${drug.genericName}`}
                      className="text-ink-subtle hover:text-ink"
                    >
                      <X className="h-4 w-4" />
                    </button>
                  </li>
                ))}
              </ul>
            )}
            {selected.length > 0 && (
              <Button variant="ghost" size="sm" onClick={() => setSelected([])}>
                Clear all
              </Button>
            )}
          </CardBody>
        </Card>

        <Card>
          <CardHeader
            title="Screening result"
            description="Curated rules only — no results are generated by a language model."
          />
          <CardBody className="space-y-3">
            {selected.length < 2 && (
              <EmptyState
                icon={Activity}
                title="Select at least two drugs"
                description="Pair screening starts once two or more drugs are selected."
              />
            )}

            {selected.length >= 2 && loading && <LoadingSkeleton rows={3} />}

            {selected.length >= 2 && !loading && pairs.length === 0 && (
              <Alert tone="success" title="No curated interaction found between the selected drugs.">
                Absence of a rule is not proof of safety. Run a patient safety check for allergy, condition and duplication
                screening.
              </Alert>
            )}

            {sortBySeverity(pairs).map((pair) => (
              <article key={`${pair.id}-${pair.drugA.id}`} className="rounded-lg border border-line px-4 py-3">
                <div className="flex flex-wrap items-center gap-2">
                  <SeverityBadge severity={pair.severity} />
                  <p className="text-sm font-semibold text-ink">
                    {pair.drugA.genericName} + {pair.drugB.genericName}
                  </p>
                </div>
                <dl className="mt-2 grid gap-2 sm:grid-cols-3">
                  <Cell label="Effect" value={pair.clinicalEffect} />
                  <Cell label="Mechanism" value={pair.mechanism} />
                  <Cell label="Management" value={pair.management} />
                </dl>
                <p className="mt-2 text-xs text-ink-muted">
                  {pair.source ? `Source: ${pair.source.name}` : 'Source not recorded'}
                  {pair.evidenceLevel ? ` · Evidence ${pair.evidenceLevel}` : ''}
                  {pair.version ? ` · Rule v${pair.version}` : ''}
                </p>
              </article>
            ))}
          </CardBody>
        </Card>
      </div>
    </>
  );
}

function Cell({ label, value }) {
  return (
    <div>
      <dt className="text-xs font-medium uppercase tracking-wide text-ink-muted">{label}</dt>
      <dd className="text-sm text-ink">{value || 'Not recorded'}</dd>
    </div>
  );
}
