'use strict';

const ROLES = Object.freeze({
  PATIENT: 'PATIENT',
  DOCTOR: 'DOCTOR',
  PHARMACIST: 'PHARMACIST',
  ADMIN: 'ADMIN',
});

const CLINICIAN_ROLES = Object.freeze([ROLES.DOCTOR, ROLES.PHARMACIST]);

const SEVERITY = Object.freeze({
  CONTRAINDICATED: 'CONTRAINDICATED',
  CRITICAL: 'CRITICAL',
  MAJOR: 'MAJOR',
  MODERATE: 'MODERATE',
  MINOR: 'MINOR',
  INFORMATIONAL: 'INFORMATIONAL',
});

// Lower index means higher clinical priority.
const SEVERITY_PRIORITY = Object.freeze([
  SEVERITY.CONTRAINDICATED,
  SEVERITY.CRITICAL,
  SEVERITY.MAJOR,
  SEVERITY.MODERATE,
  SEVERITY.MINOR,
  SEVERITY.INFORMATIONAL,
]);

const severityRank = (severity) => {
  const index = SEVERITY_PRIORITY.indexOf(severity);
  return index === -1 ? SEVERITY_PRIORITY.length : index;
};

const ALERT_SEVERITIES = Object.freeze([
  SEVERITY.CONTRAINDICATED,
  SEVERITY.CRITICAL,
  SEVERITY.MAJOR,
]);

const FINDING_CATEGORY = Object.freeze({
  DRUG_DRUG: 'DRUG_DRUG',
  DRUG_DISEASE: 'DRUG_DISEASE',
  DRUG_ALLERGY: 'DRUG_ALLERGY',
  DUPLICATION: 'DUPLICATION',
  PATIENT_FACTOR: 'PATIENT_FACTOR',
});

const FINDING_STATUS = Object.freeze({
  OPEN: 'OPEN',
  ACKNOWLEDGED: 'ACKNOWLEDGED',
  REVIEW_REQUIRED: 'REVIEW_REQUIRED',
  ACCEPTED: 'ACCEPTED',
  RESOLVED: 'RESOLVED',
});

const AUDIT_ACTIONS = Object.freeze({
  LOGIN: 'AUTH_LOGIN',
  LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
  LOGOUT: 'AUTH_LOGOUT',
  REGISTER: 'AUTH_REGISTER',
  TOKEN_REFRESH: 'AUTH_TOKEN_REFRESH',
  TOKEN_REUSE_DETECTED: 'AUTH_TOKEN_REUSE_DETECTED',
  PASSWORD_RESET_REQUESTED: 'AUTH_PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET: 'AUTH_PASSWORD_RESET',
  EMAIL_VERIFIED: 'AUTH_EMAIL_VERIFIED',
  PATIENT_ACCESS: 'PATIENT_ACCESS',
  PATIENT_UPDATE: 'PATIENT_UPDATE',
  MEDICATION_CHANGE: 'MEDICATION_CHANGE',
  PRESCRIPTION_UPLOAD: 'PRESCRIPTION_UPLOAD',
  OCR_PROCESSING: 'OCR_PROCESSING',
  RECONCILIATION: 'MEDICATION_RECONCILIATION',
  SAFETY_CHECK: 'SAFETY_CHECK',
  REVIEW_ACTION: 'CLINICIAN_REVIEW',
  REPORT_CREATED: 'REPORT_CREATED',
  REPORT_DOWNLOADED: 'REPORT_DOWNLOADED',
  ADMIN_CHANGE: 'ADMIN_CHANGE',
  AI_QUERY: 'AI_QUERY',
});

const ERROR_CODES = Object.freeze({
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  DATABASE_ERROR: 'DATABASE_ERROR',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
  OCR_ERROR: 'OCR_ERROR',
  AI_ERROR: 'AI_ERROR',
  INSUFFICIENT_VERIFIED_EVIDENCE: 'INSUFFICIENT_VERIFIED_EVIDENCE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
});

const CONFIDENCE = Object.freeze({
  AUTO_CONFIRM_MIN: 0.9,
  CANDIDATE_MIN: 0.45,
});

module.exports = {
  ROLES,
  CLINICIAN_ROLES,
  SEVERITY,
  SEVERITY_PRIORITY,
  severityRank,
  ALERT_SEVERITIES,
  FINDING_CATEGORY,
  FINDING_STATUS,
  AUDIT_ACTIONS,
  ERROR_CODES,
  CONFIDENCE,
};
