export const RuleType = {
  DRUG_DRUG: 'DRUG_DRUG',
  DRUG_DISEASE: 'DRUG_DISEASE',
  DRUG_ALLERGY: 'DRUG_ALLERGY',
  DUPLICATION: 'DUPLICATION',
  PATIENT_FACTOR: 'PATIENT_FACTOR',
};

export const DiseaseRuleType = {
  CONTRAINDICATION: 'CONTRAINDICATION',
  PRECAUTION: 'PRECAUTION',
  WARNING: 'WARNING',
};

